# Based on http://www.appveyor.com/docs/appveyor-yml

# Fix line endings in Windows. (runs before repo cloning)
init:
  - git config --global core.autocrlf input

# Test against these versions of Node.js.
environment:
  NODE_ENV: "test"
  matrix:
    - nodejs_version: "0.10"
    - nodejs_version: "0.11"
    - nodejs_version: "0.12"

# Allow failing jobs for bleeding-edge Node.js versions.
matrix:
  allow_failures:
    - nodejs_version: "0.11"
    - nodejs_version: "0.12"

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node 0.STABLE.latest
  - ps: Install-Product node $env:nodejs_version
  # Typical npm stuff.
  - npm install
  - npm i mocha -g

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  - cmd: npm run appveyor

# Don't actually build.
build: off

# Set build version format here instead of in the admin panel.
version: "{build}"